mod 'apache',
  :git => 'https://teste.com/puppetlabs/puppetlabs-apache'

mod 'apache',
  :git => 'https://teste.com/puppetlabs/puppetlabs-apache',
  :ref => 'docs_experiment'

mod 'apache',
  :git => 'https://teste.com/puppetlabs/puppetlabs-apache',
  :tag => '0.9.0'

mod 'apache',
  :git    => 'https://teste.com/puppetlabs/puppetlabs-apache',
  :commit => '83401079053dca11d61945bd9beef9ecf7576cbf'

mod 'apache',
  :git    => 'https://teste.com/puppetlabs/puppetlabs-apache',
  :branch => 'docs_experiment'

mod 'puppetlabs-apache',
  type:    'git',
  source:  'https://teste.com/puppetlabs/puppetlabs-apache',
  version: '2098a17'
